title: "Jaron Erba"
description: ""
url: "https://jaronerba.com"

# GitHub Pages / Jekyll settings
permalink: pretty

plugins:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-sitemap"

exclude:
  - "node_modules"
  - "package-lock.json"
  - "package.json"
  - "server.js"
  - "public"
  - "README.md"

defaults:
  - scope:
      path: "posts"
    values:
      layout: "post"
      nav: "posts"
